apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: { { .Values.namespace.name } }
  name: techtrends
  labels:
    app: techtrends
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: "{ { .Values.image.repository } }:{ { .Values.image.tag } }"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          name: techtrends
          resources:
            requests:
              cpu: { { .Values.resources.requests.cpu } }
              memory: { { .Values.resources.requests.memory } }
            limits:
              cpu: { { .Values.resources.limits.cpu } }
              memory: { { .Values.resources.limits.memory } }
          ports:
            - containerPort: { { .Values.service.port } }
              protocol: { { .Values.service.protocol } }
          livenessProbe:
            httpGet:
              path: /healthz
              port: { { .Values.service.port } }
          readinessProbe:
            httpGet:
              path: /healthz
              port: { { .Values.service.port } }
