apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: techtrends
  labels:
    app: techtrends
spec:
  type: ClusterIP
  selector:
    app: techtrends
  ports:
    - port: 4111
      protocol: TCP
      targetPort: 3111
